# CDN url for image location
images_path: "https://s3-sa-east-1.amazonaws.com/cdn.quiz.olook.com.br/v2"
# Randomize questions?
randomize: true
# Number of dummy questions that should be added to the quiz. They have 
# no influence on classification
num_of_dummy_questions: 3
